# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='test',
            name='age',
        ),
    ]
